"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "tr" | "en" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.yachts": "Our Yachts",
    "nav.itineraries": "Itineraries",
    "nav.destinations": "Destinations",
    "nav.about": "About Us",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.booking": "Book Now",

    // Home Hero
    "home.hero.badge": "Luxury Blue Cruise Since 1989",
    "home.hero.title": "Discover Turkey's Turquoise Coast in Ultimate Luxury",
    "home.hero.subtitle": "Experience an unforgettable blue cruise aboard our handcrafted gulets. Crystal-clear waters, ancient ruins, and five-star service await you.",
    "home.hero.cta.fleet": "Explore Our Fleet",
    "home.hero.cta.contact": "Get a Quote",

    // Home Features
    "home.features.experience.title": "35+ Years Experience",
    "home.features.experience.desc": "Trusted by thousands of guests since 1989",
    "home.features.crew.title": "Professional Crew",
    "home.features.crew.desc": "Experienced captain and attentive staff",
    "home.features.cuisine.title": "Gourmet Cuisine",
    "home.features.cuisine.desc": "Full board with Mediterranean delights",
    "home.features.certified.title": "TURSAB Certified",
    "home.features.certified.desc": "Licensed travel agency #1739",

    // Home Fleet
    "home.fleet.badge": "Our Fleet",
    "home.fleet.title": "Handcrafted Luxury Gulets",
    "home.fleet.subtitle": "Choose from our collection of beautifully maintained gulets, each offering unique character and world-class amenities.",
    "home.fleet.viewAll": "View All Yachts",

    // Home Itineraries
    "home.itineraries.badge": "Itineraries",
    "home.itineraries.title": "Explore Our Routes",
    "home.itineraries.subtitle": "Discover the best of the Turkish Riviera with our carefully curated sailing routes.",
    "home.itineraries.viewAll": "View All Itineraries",

    // Home About
    "home.about.title": "Your Gateway to the Mediterranean Dream",
    "home.about.desc1": "Since 1989, Holiday Yacht has been crafting unforgettable blue cruise experiences along Turkey's stunning Turquoise Coast. As part of the Light Tours family, we combine decades of maritime expertise with genuine Turkish hospitality.",
    "home.about.desc2": "Our fleet of handcrafted gulets represents the finest in traditional Turkish boat building, enhanced with modern comforts and amenities.",

    // Home Stats
    "home.stats.years": "Years of Excellence",
    "home.stats.yachts": "Luxury Gulets",
    "home.stats.guests": "Happy Guests",
    "home.stats.support": "Support",
    "home.stats.satisfaction": "Satisfaction",
    "home.stats.destinations": "Destinations",

    // Home Testimonials
    "home.testimonials.badge": "Testimonials",
    "home.testimonials.title": "What Our Guests Say",
    "home.testimonial1": "An absolutely magical experience! The crew was exceptional, the food was incredible, and the scenery was breathtaking. We'll definitely be back!",
    "home.testimonial2": "From booking to disembarkation, everything was perfect. The yacht was beautiful and immaculately maintained. Best holiday we've ever had!",
    "home.testimonial3": "The attention to detail is remarkable. Swimming in crystal-clear bays and dining under the stars - it doesn't get better than this.",

    // Home CTA
    "home.cta.title": "Ready for Your Dream Voyage?",
    "home.cta.subtitle": "Let us help you plan the perfect blue cruise experience. Contact us today for a personalized quote.",
    "home.cta.button": "Plan Your Voyage",

    // Home Partners
    "home.partners.partOf": "Part of",

    // Yachts Page
    "yachts.badge": "Premium Gulet Collection",
    "yachts.title": "Our Fleet",
    "yachts.subtitle": "Discover our handpicked selection of luxury gulets, each offering exceptional comfort and authentic Turkish craftsmanship.",
    "yachts.stats.gulets": "Luxury Gulets",
    "yachts.stats.capacity": "Guest Capacity",
    "yachts.stats.length": "Length Range",
    "yachts.stats.builtYears": "Built Years",
    "yachts.featured": "Featured Yacht",
    "yachts.allYachts": "All Yachts",
    "yachts.whyChoose": "Why Choose Our Fleet?",
    "yachts.whyChooseDesc": "Every yacht in our fleet meets the highest standards of safety, comfort, and luxury.",
    "yachts.why.quality.title": "Premium Quality",
    "yachts.why.quality.desc": "Each gulet is handcrafted by master shipbuilders using traditional techniques and the finest materials.",
    "yachts.why.crew.title": "Expert Crew",
    "yachts.why.crew.desc": "Our professional crew members are trained to provide exceptional service while ensuring your safety.",
    "yachts.why.amenities.title": "Modern Amenities",
    "yachts.why.amenities.desc": "Enjoy contemporary comforts including air conditioning, WiFi, and entertainment systems.",

    // Yacht Filters
    "yachts.filters.title": "Filter Yachts",
    "yachts.filters.guests": "Guests",
    "yachts.filters.length": "Length",
    "yachts.filters.weeklyPrice": "Weekly Price",
    "yachts.filters.anyGuests": "Any capacity",
    "yachts.filters.anyLength": "Any length",
    "yachts.filters.anyPrice": "Any price",
    "yachts.filters.under15k": "Under €15,000",
    "yachts.filters.under20k": "Under €20,000",
    "yachts.filters.under25k": "Under €25,000",
    "yachts.filters.clear": "Clear filters",
    "yachts.filters.active": "Active",
    "yachts.filters.noResults": "No yachts match your filters",
    "yachts.filters.noResultsDesc": "Try adjusting your filter criteria",

    // Yacht Details
    "yacht.cabins": "Cabins",
    "yacht.guests": "Guests",
    "yacht.length": "Length",
    "yacht.crew": "Crew",
    "yacht.priceFrom": "From",
    "yacht.perWeek": "/week",
    "yacht.bookNow": "Book This Yacht",
    "yacht.requestQuote": "Request Quote",
    "yacht.amenities": "Amenities",
    "yacht.specifications": "Specifications",
    "yacht.gallery": "Gallery",
    "yacht.overview": "Overview",
    "yacht.features": "Features",
    "yacht.seasonPrices": "Seasonal Prices",
    "yacht.lowSeason": "Low Season",
    "yacht.midSeason": "Mid Season",
    "yacht.highSeason": "High Season",

    // Booking
    "booking.title": "Book Your Charter",
    "booking.subtitle": "Check availability and reserve your dream yacht in just a few steps.",
    "booking.selectYacht": "Select Your Yacht",
    "booking.selectYachtDesc": "Choose from our fleet of luxury gulets.",
    "booking.selectDates": "Select Your Dates",
    "booking.minNights": "Min. 7 nights",
    "booking.available": "Available",
    "booking.booked": "Booked",
    "booking.selected": "Selected",
    "booking.checkIn": "Check-in",
    "booking.checkOut": "Check-out",
    "booking.duration": "Duration",
    "booking.nights": "nights",
    "booking.guestDetails": "Guest Details",
    "booking.firstName": "First Name",
    "booking.lastName": "Last Name",
    "booking.email": "Email Address",
    "booking.phone": "Phone Number",
    "booking.country": "Country",
    "booking.guests": "Number of Guests",
    "booking.specialRequests": "Special Requests",
    "booking.submit": "Request Booking",
    "booking.changeYacht": "← Change Yacht",
    "booking.whyBookDirect": "Why Book Directly With Us?",
    "booking.bestPrice": "Best Price Guarantee",
    "booking.noHiddenFees": "No Hidden Fees",
    "booking.flexibleCancellation": "Flexible Cancellation",
    "booking.support247": "24/7 Support",
    "booking.needHelp": "Need help with your booking?",

    // Booking Form
    "bookingForm.confirmation": "Confirmation",
    "bookingForm.priceSummary": "Price Summary",
    "bookingForm.fullBoardIncluded": "Full board included",
    "bookingForm.total": "Total",
    "bookingForm.continueToDetails": "Continue to Details",
    "bookingForm.guestInfo": "Guest Information",
    "bookingForm.firstNameRequired": "First name is required",
    "bookingForm.lastNameRequired": "Last name is required",
    "bookingForm.emailRequired": "Email is required",
    "bookingForm.emailInvalid": "Invalid email address",
    "bookingForm.phoneRequired": "Phone is required",
    "bookingForm.countryRequired": "Country is required",
    "bookingForm.guest": "guest",
    "bookingForm.specialRequestsPlaceholder": "Any dietary requirements, special occasions, or preferences...",
    "bookingForm.agreeToTerms": "I agree to the",
    "bookingForm.termsConditions": "Terms & Conditions",
    "bookingForm.and": "and",
    "bookingForm.privacyPolicy": "Privacy Policy",
    "bookingForm.termsRequired": "You must agree to the terms",
    "bookingForm.back": "Back",
    "bookingForm.requestSubmitted": "Booking Request Submitted!",
    "bookingForm.thankYou": "Thank you for your interest in",
    "bookingForm.willContact": "Our team will review your request and contact you within 24 hours to confirm your booking.",
    "bookingForm.bookingSummary": "Booking Summary",
    "bookingForm.yacht": "Yacht",
    "bookingForm.dates": "Dates",
    "bookingForm.returnHome": "Return to Homepage",

    // Calendar
    "calendar.selectDates": "Select Your Dates",
    "calendar.minNights": "Min. {min} nights",
    "calendar.available": "Available",
    "calendar.booked": "Booked",
    "calendar.selected": "Selected",
    "calendar.checkIn": "Check-in",
    "calendar.checkOut": "Check-out",
    "calendar.duration": "Duration",
    "calendar.nights": "nights",
    "calendar.minNightsWarning": "Please select at least {min} nights",

    // Yacht Detail Page
    "yachtDetail.backToFleet": "Back to Fleet",
    "yachtDetail.about": "About",
    "yachtDetail.photoGallery": "Photo Gallery",
    "yachtDetail.amenitiesFeatures": "Amenities & Features",
    "yachtDetail.startingFrom": "Starting from",
    "yachtDetail.perWeek": "per week",
    "yachtDetail.callForQuote": "Call for Quote",
    "yachtDetail.sendInquiry": "Send Inquiry",
    "yachtDetail.charterIncludes": "Charter includes:",
    "yachtDetail.professionalCrew": "Professional crew",
    "yachtDetail.fullBoardMeals": "Full board meals",
    "yachtDetail.fuelCruising": "Fuel for cruising",
    "yachtDetail.waterSports": "Water sports equipment",
    "yachtDetail.portFees": "Port fees",
    "yachtDetail.built": "Built",
    "yachtDetail.renovated": "Renovated",

    // Itinerary Detail Page
    "itineraryDetail.allItineraries": "All Itineraries",
    "itineraryDetail.days": "Days",
    "itineraryDetail.dayByDay": "Day by Day Itinerary",
    "itineraryDetail.dayByDayDesc": "Your journey unfolds with carefully planned stops, activities, and experiences designed to showcase the best of the region.",
    "itineraryDetail.recommendedYachts": "Recommended Yachts",
    "itineraryDetail.recommendedYachtsDesc": "These yachts are perfectly suited for this itinerary, offering the ideal combination of comfort and capability.",
    "itineraryDetail.readyToExperience": "Ready to Experience This Route?",
    "itineraryDetail.contactUs": "Contact us to check availability and receive a personalized quote for your dream sailing adventure.",
    "itineraryDetail.getQuote": "Get a Quote",

    // Contact
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions or ready to book your dream voyage?",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.address": "Address",
    "contact.workingHours": "Working Hours",
    "contact.sendMessage": "Send Us a Message",
    "contact.sendMessageDesc": "Fill out the form and we'll get back to you within 24 hours.",
    "contact.yourName": "Your Name",
    "contact.yourEmail": "Email Address",
    "contact.phoneNumber": "Phone Number",
    "contact.subject": "Subject",
    "contact.selectSubject": "Select a subject",
    "contact.subjectBooking": "Booking Inquiry",
    "contact.subjectQuote": "Request a Quote",
    "contact.subjectInfo": "General Information",
    "contact.subjectCustom": "Custom Itinerary",
    "contact.subjectOther": "Other",
    "contact.interestedYacht": "Interested in a Yacht?",
    "contact.selectYacht": "Select a yacht (optional)",
    "contact.yourMessage": "Your Message",
    "contact.messagePlaceholder": "Tell us about your dream voyage...",
    "contact.send": "Send Message",
    "contact.messageSent": "Message Sent!",
    "contact.messageSentDesc": "Thank you for contacting us.",
    "contact.sendAnother": "Send Another Message",
    "contact.immediateHelp": "Need Immediate Help?",
    "contact.immediateHelpDesc": "Our team is available during business hours.",

    // About
    "about.badge": "Since 1989",
    "about.title": "About Holiday Yacht",
    "about.subtitle": "Over three decades of crafting unforgettable blue cruise experiences.",
    "about.stats.years": "Years Experience",
    "about.stats.gulets": "Luxury Gulets",
    "about.stats.guests": "Happy Guests",
    "about.stats.destinations": "Destinations",
    "about.story.badge": "Our Story",
    "about.story.title": "A Legacy of Excellence on the Turquoise Coast",
    "about.story.p1": "Founded in 1989 in the charming coastal town of Fethiye, Holiday Yacht began with a simple vision: to share the breathtaking beauty of Turkey's Mediterranean coastline with travelers from around the world.",
    "about.story.p2": "As part of the Light Tours family, we have grown from a small local operation into one of the region's most respected yacht charter companies.",
    "about.story.p3": "Today, we continue to uphold the values that have guided us for over 35 years: exceptional service, authentic experiences, and an unwavering commitment to guest satisfaction.",
    "about.values.badge": "Our Values",
    "about.values.title": "What Sets Us Apart",
    "about.values.safety": "Safety First",
    "about.values.safetyDesc": "Your safety is our top priority.",
    "about.values.hospitality": "Genuine Hospitality",
    "about.values.hospitalityDesc": "Experience authentic Turkish hospitality.",
    "about.values.excellence": "Excellence",
    "about.values.excellenceDesc": "We strive for excellence in every aspect.",
    "about.values.personal": "Personal Touch",
    "about.values.personalDesc": "Every charter is tailored to your preferences.",
    "about.team.badge": "Our Team",
    "about.team.title": "Meet the Crew",
    "about.team.subtitle": "Our experienced crew members are the heart of Holiday Yacht.",
    "about.team.captain": "Captain",
    "about.team.captainDesc": "Expert navigators with decades of experience.",
    "about.team.chef": "Chef",
    "about.team.chefDesc": "Culinary artists creating delicious Mediterranean cuisine.",
    "about.team.crew": "Crew",
    "about.team.crewDesc": "Attentive staff ensuring your comfort and safety.",
    "about.cta.title": "Ready to Start Your Journey?",
    "about.cta.subtitle": "Let us help you create memories that will last a lifetime.",
    "about.cta.fleet": "Explore Our Fleet",
    "about.cta.contact": "Contact Us",
    "about.lightTours.title": "Part of the Light Tours Family",
    "about.lightTours.desc": "Holiday Yacht is proud to be part of Light Tours, a comprehensive travel agency.",

    // Itineraries
    "itineraries.badge": "Curated Routes",
    "itineraries.title": "Sailing Itineraries",
    "itineraries.subtitle": "Discover the magic of the Turkish Riviera with our expertly planned routes.",
    "itineraries.days": "Days",
    "itineraries.highlights": "Highlights",
    "itineraries.viewFull": "View Full Itinerary",
    "itineraries.dayByDay": "Day by Day Itinerary",
    "itineraries.dayByDayDesc": "Your journey unfolds with carefully planned stops and experiences.",
    "itineraries.recommendedYachts": "Recommended Yachts",
    "itineraries.recommendedYachtsDesc": "These yachts are perfectly suited for this itinerary.",
    "itineraries.customRoute": "Looking for a Custom Route?",
    "itineraries.customRouteDesc": "We can create a personalized itinerary based on your preferences.",
    "itineraries.requestCustom": "Request Custom Itinerary",
    "itineraries.readyToExperience": "Ready to Experience This Route?",
    "itineraries.checkAvailability": "Check Availability",
    "itineraries.getQuote": "Get a Quote",
    "itineraries.allRoutes": "All Itineraries",

    // Error Pages
    "error.pageNotFound": "Page Not Found",
    "error.pageNotFoundDesc": "The page you're looking for seems to have sailed away. Perhaps it's exploring the Turkish coast!",
    "error.backToHome": "Back to Home",
    "error.viewFleet": "View Our Fleet",
    "error.contactUs": "Contact Us",

    // Footer
    "footer.description": "Premium gulet charters along Turkey's stunning Turquoise Coast since 1989.",
    "footer.quickLinks": "Quick Links",
    "footer.contactInfo": "Contact Info",
    "footer.followUs": "Follow Us",
    "footer.rights": "All rights reserved.",
    "footer.tursab": "TURSAB License #1739",
    "footer.workingHours": "Mon - Sat: 09:00 - 18:00",

    // Common
    "common.select": "Select",
    "common.viewDetails": "View Details",
    "common.learnMore": "Learn More",
    "common.callUs": "Call Us",

    // Search
    "search.placeholder": "Search yachts, destinations, itineraries...",
    "search.noResults": "No results found",
    "search.quickLinks": "Quick Links",
    "search.hint": "Type to search",
    "search.toClose": "to close",

    // Favorites
    "favorites.title": "My Favorites",
    "favorites.subtitle": "Your saved yachts and itineraries",
    "favorites.empty": "No favorites yet",
    "favorites.emptyDesc": "Save yachts and itineraries you love by clicking the heart icon",
    "favorites.browseYachts": "Browse Yachts",
    "favorites.browseItineraries": "Browse Itineraries",
    "favorites.yachts": "Yachts",
    "favorites.itineraries": "Itineraries",
    "favorites.destinations": "Destinations",
    "favorites.clearAll": "Clear All",
    "favorites.addedToFavorites": "Added to favorites",
    "favorites.removedFromFavorites": "Removed from favorites",

    "common.whatsapp": "WhatsApp",
    "common.loading": "Loading...",
    "common.from": "From",
    "common.perWeek": "per week",
    "common.share": "Share",

    // Blog
    "blog.badge": "Our Blog",
    "blog.title": "Blue Cruise Insights & Travel Tips",
    "blog.subtitle": "Expert advice, destination guides, and insider tips for your perfect yacht charter experience",
    "blog.allPosts": "All Posts",
    "blog.destinations": "Destinations",
    "blog.tips": "Tips & Advice",
    "blog.guides": "Guides",
    "blog.news": "News",
    "blog.readMore": "Read More",
    "blog.minRead": "min read",
    "blog.backToBlog": "Back to Blog",
    "blog.relatedArticles": "Related Articles",
    "blog.moreFromBlog": "More from Our Blog",
    "blog.popularTopics": "Popular Topics",
    "blog.readyForCruise": "Ready for Your Blue Cruise?",
    "blog.contactUsDesc": "Contact us to plan your perfect yacht charter experience along the Turkish coast.",
    "blog.getQuote": "Get a Quote",
    "blog.stayUpdated": "Stay Updated with Our Latest Articles",
    "blog.subscribeDesc": "Subscribe to our newsletter for exclusive travel tips, special offers, and insider guides to the Turkish coast.",
    "blog.subscribeNow": "Subscribe Now",
    "blog.shareArticle": "Share this article:",
    "blog.noPosts": "No posts found in this category.",

    // Destinations
    "destinations.badge": "Explore Turkey",
    "destinations.title": "Sailing Destinations",
    "destinations.subtitle": "Discover the stunning harbors and coastal gems of Turkey's Turquoise Coast, each offering unique experiences for your Blue Cruise adventure",
    "destinations.turquoiseAwaits": "The Turquoise Coast Awaits",
    "destinations.turquoiseDesc": "Turkey's southwestern coast is home to some of the Mediterranean's most spectacular sailing waters. From ancient harbor towns to pristine bays, each destination offers its own character and attractions.",
    "destinations.explore": "Explore",
    "destinations.notSure": "Not Sure Where to Start?",
    "destinations.notSureDesc": "Our team knows every bay and harbor along the Turkish coast. Let us help you choose the perfect itinerary for your dream Blue Cruise.",
    "destinations.contactExperts": "Contact Our Experts",
    "destinations.about": "About",
    "destinations.whyVisit": "Why Visit",
    "destinations.mustSee": "Must-See Attractions",
    "destinations.itinerariesFrom": "Itineraries from",
    "destinations.planCruise": "Plan Your",
    "destinations.planCruiseDesc": "Contact us to start planning your perfect Blue Cruise from",
    "destinations.idealFor": "Ideal For",
    "destinations.bestTime": "Best Time to Visit",
    "destinations.sailInStyle": "Sail",
    "destinations.sailInStyleDesc": "Explore our fleet of luxury gulets, all available for charters from",
    "destinations.exploreOther": "Explore Other Destinations",
    "destinations.viewAll": "View All Destinations",
    "destinations.allDestinations": "All Destinations",
    "destinations.turkey": "Turkey",

    // Newsletter
    "newsletter.title": "Subscribe to Our Newsletter",
    "newsletter.subtitle": "Get exclusive travel tips, special offers, and insider guides to the Turkish coast delivered to your inbox.",
    "newsletter.placeholder": "Enter your email address",
    "newsletter.subscribe": "Subscribe Now",
    "newsletter.subscribing": "Subscribing...",
    "newsletter.success": "Thank you for subscribing! Check your inbox for a confirmation email.",
    "newsletter.error": "Something went wrong. Please try again later.",
    "newsletter.invalidEmail": "Please enter a valid email address",
    "newsletter.required": "Please enter your email address",
    "newsletter.privacy": "No spam, unsubscribe anytime. We respect your privacy.",
    "newsletter.compact.title": "Newsletter",
    "newsletter.compact.subtitle": "Get travel tips & exclusive offers",
    "newsletter.compact.subscribed": "Subscribed!",
  },
  tr: {
    // Navigation
    "nav.home": "Ana Sayfa",
    "nav.yachts": "Yatlarımız",
    "nav.itineraries": "Rotalar",
    "nav.destinations": "Destinasyonlar",
    "nav.about": "Hakkımızda",
    "nav.blog": "Blog",
    "nav.contact": "İletişim",
    "nav.booking": "Rezervasyon",

    // Home Hero
    "home.hero.badge": "1989'dan Beri Lüks Mavi Yolculuk",
    "home.hero.title": "Türkiye'nin Turkuaz Kıyılarını Lüks İçinde Keşfedin",
    "home.hero.subtitle": "El yapımı guletlerimizde unutulmaz bir mavi yolculuk deneyimi yaşayın. Kristal berraklığında sular, antik kalıntılar ve beş yıldızlı hizmet sizi bekliyor.",
    "home.hero.cta.fleet": "Filomuzu Keşfedin",
    "home.hero.cta.contact": "Teklif Alın",

    // Home Features
    "home.features.experience.title": "35+ Yıl Deneyim",
    "home.features.experience.desc": "1989'dan beri binlerce misafirin güvendiği",
    "home.features.crew.title": "Profesyonel Ekip",
    "home.features.crew.desc": "Deneyimli kaptan ve özenli personel",
    "home.features.cuisine.title": "Gurme Mutfak",
    "home.features.cuisine.desc": "Akdeniz lezzetleriyle tam pansiyon",
    "home.features.certified.title": "TÜRSAB Belgeli",
    "home.features.certified.desc": "Lisanslı seyahat acentası #1739",

    // Home Fleet
    "home.fleet.badge": "Filomuz",
    "home.fleet.title": "El Yapımı Lüks Guletler",
    "home.fleet.subtitle": "Her biri benzersiz karakter ve dünya standartlarında olanaklar sunan özenle bakılan guletlerimizden seçim yapın.",
    "home.fleet.viewAll": "Tüm Yatları Gör",

    // Home Itineraries
    "home.itineraries.badge": "Rotalar",
    "home.itineraries.title": "Rotalarımızı Keşfedin",
    "home.itineraries.subtitle": "Özenle hazırlanmış yelken rotalarımızla Türk Rivierası'nın en güzel yerlerini keşfedin.",
    "home.itineraries.viewAll": "Tüm Rotaları Gör",

    // Home About
    "home.about.title": "Akdeniz Rüyasına Açılan Kapınız",
    "home.about.desc1": "1989'dan beri Holiday Yacht, Türkiye'nin muhteşem Turkuaz Kıyıları boyunca unutulmaz mavi yolculuk deneyimleri sunuyor. Light Tours ailesinin bir parçası olarak, onlarca yıllık denizcilik uzmanlığını gerçek Türk misafirperverliğiyle birleştiriyoruz.",
    "home.about.desc2": "El yapımı gulet filomuz, modern konfor ve olanaklarla güçlendirilmiş geleneksel Türk tekne yapımının en iyisini temsil ediyor.",

    // Home Stats
    "home.stats.years": "Yıllık Mükemmellik",
    "home.stats.yachts": "Lüks Gulet",
    "home.stats.guests": "Mutlu Misafir",
    "home.stats.support": "Destek",
    "home.stats.satisfaction": "Memnuniyet",
    "home.stats.destinations": "Destinasyon",

    // Home Testimonials
    "home.testimonials.badge": "Misafir Yorumları",
    "home.testimonials.title": "Misafirlerimiz Ne Diyor",
    "home.testimonial1": "Kesinlikle büyülü bir deneyim! Ekip olağanüstüydü, yemekler inanılmazdı ve manzara nefes kesiciydi. Kesinlikle tekrar geleceğiz!",
    "home.testimonial2": "Rezervasyondan inişe kadar her şey mükemmeldi. Yat güzeldi ve kusursuz bakılıydı. Yaptığımız en iyi tatil!",
    "home.testimonial3": "Detaylara gösterilen özen dikkat çekici. Kristal berraklığında koylarda yüzmek ve yıldızların altında yemek yemek - bundan iyisi olamaz.",

    // Home CTA
    "home.cta.title": "Hayalinizdeki Yolculuğa Hazır mısınız?",
    "home.cta.subtitle": "Mükemmel mavi yolculuk deneyiminizi planlamamıza yardımcı olalım. Kişisel teklif için bugün bize ulaşın.",
    "home.cta.button": "Yolculuğunuzu Planlayın",

    // Home Partners
    "home.partners.partOf": "Bir parçası",

    // Yachts Page
    "yachts.badge": "Premium Gulet Koleksiyonu",
    "yachts.title": "Filomuz",
    "yachts.subtitle": "El yapımı seçkin guletlerimizi keşfedin. Her biri olağanüstü konfor ve otantik Türk işçiliği sunuyor.",
    "yachts.stats.gulets": "Lüks Gulet",
    "yachts.stats.capacity": "Misafir Kapasitesi",
    "yachts.stats.length": "Uzunluk Aralığı",
    "yachts.stats.builtYears": "Yapım Yılları",
    "yachts.featured": "Öne Çıkan Yat",
    "yachts.allYachts": "Tüm Yatlar",
    "yachts.whyChoose": "Filomuzu Neden Tercih Etmelisiniz?",
    "yachts.whyChooseDesc": "Filomizdeki her yat en yüksek güvenlik, konfor ve lüks standartlarını karşılamaktadır.",
    "yachts.why.quality.title": "Premium Kalite",
    "yachts.why.quality.desc": "Her gulet, geleneksel teknikler ve en kaliteli malzemeler kullanılarak usta gemi yapımcıları tarafından el işçiliğiyle üretilmiştir.",
    "yachts.why.crew.title": "Uzman Ekip",
    "yachts.why.crew.desc": "Profesyonel mürettebatımız güvenliğinizi sağlarken olağanüstü hizmet sunmak için eğitilmiştir.",
    "yachts.why.amenities.title": "Modern Olanaklar",
    "yachts.why.amenities.desc": "Klima, WiFi ve eğlence sistemleri dahil çağdaş konforun tadını çıkarın.",

    // Yacht Filters
    "yachts.filters.title": "Yatları Filtrele",
    "yachts.filters.guests": "Misafir",
    "yachts.filters.length": "Uzunluk",
    "yachts.filters.weeklyPrice": "Haftalık Fiyat",
    "yachts.filters.anyGuests": "Herhangi kapasite",
    "yachts.filters.anyLength": "Herhangi uzunluk",
    "yachts.filters.anyPrice": "Herhangi fiyat",
    "yachts.filters.under15k": "€15.000 altı",
    "yachts.filters.under20k": "€20.000 altı",
    "yachts.filters.under25k": "€25.000 altı",
    "yachts.filters.clear": "Filtreleri temizle",
    "yachts.filters.active": "Aktif",
    "yachts.filters.noResults": "Filtrelerinize uyan yat bulunamadı",
    "yachts.filters.noResultsDesc": "Filtre kriterlerinizi değiştirmeyi deneyin",

    // Yacht Details
    "yacht.cabins": "Kabin",
    "yacht.guests": "Misafir",
    "yacht.length": "Uzunluk",
    "yacht.crew": "Mürettebat",
    "yacht.priceFrom": "Başlayan",
    "yacht.perWeek": "/hafta",
    "yacht.bookNow": "Bu Yatı Rezerve Et",
    "yacht.requestQuote": "Teklif İste",
    "yacht.amenities": "Olanaklar",
    "yacht.specifications": "Teknik Özellikler",
    "yacht.gallery": "Galeri",
    "yacht.overview": "Genel Bakış",
    "yacht.features": "Özellikler",
    "yacht.seasonPrices": "Sezon Fiyatları",
    "yacht.lowSeason": "Düşük Sezon",
    "yacht.midSeason": "Orta Sezon",
    "yacht.highSeason": "Yüksek Sezon",

    // Booking
    "booking.title": "Charter Rezervasyonu",
    "booking.subtitle": "Müsaitliği kontrol edin ve hayalinizdeki yatı birkaç adımda rezerve edin.",
    "booking.selectYacht": "Yatınızı Seçin",
    "booking.selectYachtDesc": "Lüks gulet filomuzdan seçim yapın.",
    "booking.selectDates": "Tarihlerinizi Seçin",
    "booking.minNights": "Min. 7 gece",
    "booking.available": "Müsait",
    "booking.booked": "Dolu",
    "booking.selected": "Seçili",
    "booking.checkIn": "Giriş",
    "booking.checkOut": "Çıkış",
    "booking.duration": "Süre",
    "booking.nights": "gece",
    "booking.guestDetails": "Misafir Bilgileri",
    "booking.firstName": "Ad",
    "booking.lastName": "Soyad",
    "booking.email": "E-posta Adresi",
    "booking.phone": "Telefon Numarası",
    "booking.country": "Ülke",
    "booking.guests": "Misafir Sayısı",
    "booking.specialRequests": "Özel İstekler",
    "booking.submit": "Rezervasyon Talebi Gönder",
    "booking.changeYacht": "← Yat Değiştir",
    "booking.whyBookDirect": "Neden Doğrudan Bizden Rezervasyon Yapmalısınız?",
    "booking.bestPrice": "En İyi Fiyat Garantisi",
    "booking.noHiddenFees": "Gizli Ücret Yok",
    "booking.flexibleCancellation": "Esnek İptal",
    "booking.support247": "7/24 Destek",
    "booking.needHelp": "Rezervasyonunuzla ilgili yardıma mı ihtiyacınız var?",

    // Booking Form
    "bookingForm.confirmation": "Onay",
    "bookingForm.priceSummary": "Fiyat Özeti",
    "bookingForm.fullBoardIncluded": "Tam pansiyon dahil",
    "bookingForm.total": "Toplam",
    "bookingForm.continueToDetails": "Detaylara Devam Et",
    "bookingForm.guestInfo": "Misafir Bilgileri",
    "bookingForm.firstNameRequired": "Ad gerekli",
    "bookingForm.lastNameRequired": "Soyad gerekli",
    "bookingForm.emailRequired": "E-posta gerekli",
    "bookingForm.emailInvalid": "Geçersiz e-posta adresi",
    "bookingForm.phoneRequired": "Telefon gerekli",
    "bookingForm.countryRequired": "Ülke gerekli",
    "bookingForm.guest": "misafir",
    "bookingForm.specialRequestsPlaceholder": "Diyet gereksinimleri, özel günler veya tercihler...",
    "bookingForm.agreeToTerms": "Kabul ediyorum:",
    "bookingForm.termsConditions": "Şartlar ve Koşullar",
    "bookingForm.and": "ve",
    "bookingForm.privacyPolicy": "Gizlilik Politikası",
    "bookingForm.termsRequired": "Şartları kabul etmelisiniz",
    "bookingForm.back": "Geri",
    "bookingForm.requestSubmitted": "Rezervasyon Talebi Gönderildi!",
    "bookingForm.thankYou": "İlginiz için teşekkür ederiz:",
    "bookingForm.willContact": "Ekibimiz talebinizi inceleyecek ve rezervasyonunuzu onaylamak için 24 saat içinde sizinle iletişime geçecektir.",
    "bookingForm.bookingSummary": "Rezervasyon Özeti",
    "bookingForm.yacht": "Yat",
    "bookingForm.dates": "Tarihler",
    "bookingForm.returnHome": "Ana Sayfaya Dön",

    // Calendar
    "calendar.selectDates": "Tarihlerinizi Seçin",
    "calendar.minNights": "Min. {min} gece",
    "calendar.available": "Müsait",
    "calendar.booked": "Rezerveli",
    "calendar.selected": "Seçili",
    "calendar.checkIn": "Giriş",
    "calendar.checkOut": "Çıkış",
    "calendar.duration": "Süre",
    "calendar.nights": "gece",
    "calendar.minNightsWarning": "Lütfen en az {min} gece seçin",

    // Yacht Detail Page
    "yachtDetail.backToFleet": "Filoya Dön",
    "yachtDetail.about": "Hakkında",
    "yachtDetail.photoGallery": "Fotoğraf Galerisi",
    "yachtDetail.amenitiesFeatures": "Olanaklar ve Özellikler",
    "yachtDetail.startingFrom": "Başlayan fiyat",
    "yachtDetail.perWeek": "haftalık",
    "yachtDetail.callForQuote": "Teklif için Arayın",
    "yachtDetail.sendInquiry": "Sorgu Gönder",
    "yachtDetail.charterIncludes": "Charter şunları içerir:",
    "yachtDetail.professionalCrew": "Profesyonel mürettebat",
    "yachtDetail.fullBoardMeals": "Tam pansiyon yemekler",
    "yachtDetail.fuelCruising": "Seyir yakıtı",
    "yachtDetail.waterSports": "Su sporları ekipmanı",
    "yachtDetail.portFees": "Liman ücretleri",
    "yachtDetail.built": "Yapım yılı",
    "yachtDetail.renovated": "Yenilenme",

    // Itinerary Detail Page
    "itineraryDetail.allItineraries": "Tüm Rotalar",
    "itineraryDetail.days": "Gün",
    "itineraryDetail.dayByDay": "Günlük Program",
    "itineraryDetail.dayByDayDesc": "Yolculuğunuz, bölgenin en iyilerini sergilemek için tasarlanmış özenle planlanmış duraklar, aktiviteler ve deneyimlerle açılır.",
    "itineraryDetail.recommendedYachts": "Önerilen Yatlar",
    "itineraryDetail.recommendedYachtsDesc": "Bu yatlar, konfor ve kapasitenin ideal kombinasyonunu sunarak bu rota için mükemmel şekilde uygundur.",
    "itineraryDetail.readyToExperience": "Bu Rotayı Deneyimlemeye Hazır mısınız?",
    "itineraryDetail.contactUs": "Hayalinizdeki yelken macerası için müsaitliği kontrol etmek ve kişiselleştirilmiş teklif almak için bizimle iletişime geçin.",
    "itineraryDetail.getQuote": "Teklif Al",

    // Contact
    "contact.title": "İletişim",
    "contact.subtitle": "Sorularınız mı var veya hayalinizdeki yolculuğu rezerve etmeye hazır mısınız?",
    "contact.phone": "Telefon",
    "contact.email": "E-posta",
    "contact.address": "Adres",
    "contact.workingHours": "Çalışma Saatleri",
    "contact.sendMessage": "Bize Mesaj Gönderin",
    "contact.sendMessageDesc": "Formu doldurun, 24 saat içinde size dönüş yapacağız.",
    "contact.yourName": "Adınız",
    "contact.yourEmail": "E-posta Adresiniz",
    "contact.phoneNumber": "Telefon Numarası",
    "contact.subject": "Konu",
    "contact.selectSubject": "Bir konu seçin",
    "contact.subjectBooking": "Rezervasyon Sorgusu",
    "contact.subjectQuote": "Teklif Talebi",
    "contact.subjectInfo": "Genel Bilgi",
    "contact.subjectCustom": "Özel Rota",
    "contact.subjectOther": "Diğer",
    "contact.interestedYacht": "İlgilendiğiniz Yat?",
    "contact.selectYacht": "Bir yat seçin (isteğe bağlı)",
    "contact.yourMessage": "Mesajınız",
    "contact.messagePlaceholder": "Hayalinizdeki yolculuğu bize anlatın...",
    "contact.send": "Mesaj Gönder",
    "contact.messageSent": "Mesaj Gönderildi!",
    "contact.messageSentDesc": "Bizimle iletişime geçtiğiniz için teşekkürler.",
    "contact.sendAnother": "Başka Mesaj Gönder",
    "contact.immediateHelp": "Acil Yardıma mı İhtiyacınız Var?",
    "contact.immediateHelpDesc": "Ekibimiz çalışma saatleri içinde hizmetinizdedir.",

    // About
    "about.badge": "1989'dan Beri",
    "about.title": "Holiday Yacht Hakkında",
    "about.subtitle": "Otuz yılı aşkın süredir unutulmaz mavi yolculuk deneyimleri sunuyoruz.",
    "about.stats.years": "Yıllık Deneyim",
    "about.stats.gulets": "Lüks Gulet",
    "about.stats.guests": "Mutlu Misafir",
    "about.stats.destinations": "Destinasyon",
    "about.story.badge": "Hikayemiz",
    "about.story.title": "Turkuaz Kıyıları'nda Mükemmellik Mirası",
    "about.story.p1": "1989 yılında şirin kıyı kasabası Fethiye'de kurulan Holiday Yacht, basit bir vizyonla başladı: Türkiye'nin Akdeniz kıyılarının nefes kesici güzelliğini dünyadan gelen gezginlerle paylaşmak.",
    "about.story.p2": "Light Tours ailesinin bir parçası olarak, küçük bir yerel işletmeden bölgenin en saygın yat kiralama şirketlerinden birine dönüştük.",
    "about.story.p3": "Bugün, 35 yılı aşkın süredir bize yol gösteren değerleri sürdürüyoruz: olağanüstü hizmet, otantik deneyimler ve misafir memnuniyetine sarsılmaz bağlılık.",
    "about.values.badge": "Değerlerimiz",
    "about.values.title": "Bizi Farklı Kılan",
    "about.values.safety": "Önce Güvenlik",
    "about.values.safetyDesc": "Güvenliğiniz en büyük önceliğimizdir.",
    "about.values.hospitality": "Gerçek Misafirperverlik",
    "about.values.hospitalityDesc": "Otantik Türk misafirperverliğini deneyimleyin.",
    "about.values.excellence": "Mükemmellik",
    "about.values.excellenceDesc": "Her aşamada mükemmellik için çabalıyoruz.",
    "about.values.personal": "Kişisel Dokunuş",
    "about.values.personalDesc": "Her charter tercihlerinize göre özelleştirilir.",
    "about.team.badge": "Ekibimiz",
    "about.team.title": "Mürettebatla Tanışın",
    "about.team.subtitle": "Deneyimli mürettebat üyelerimiz Holiday Yacht'ın kalbidir.",
    "about.team.captain": "Kaptan",
    "about.team.captainDesc": "Onlarca yıllık deneyime sahip uzman denizciler.",
    "about.team.chef": "Şef",
    "about.team.chefDesc": "Lezzetli Akdeniz mutfağı yaratan mutfak sanatçıları.",
    "about.team.crew": "Mürettebat",
    "about.team.crewDesc": "Konforunuzu ve güvenliğinizi sağlayan özenli personel.",
    "about.cta.title": "Yolculuğunuza Başlamaya Hazır mısınız?",
    "about.cta.subtitle": "Ömür boyu sürecek anılar yaratmanıza yardımcı olalım.",
    "about.cta.fleet": "Filomuzu Keşfedin",
    "about.cta.contact": "Bize Ulaşın",
    "about.lightTours.title": "Light Tours Ailesinin Bir Parçası",
    "about.lightTours.desc": "Holiday Yacht, kapsamlı bir seyahat acentası olan Light Tours'un gurur duyduğu bir parçasıdır.",

    // Itineraries
    "itineraries.badge": "Özel Rotalar",
    "itineraries.title": "Yelken Rotaları",
    "itineraries.subtitle": "Uzman ekibimiz tarafından planlanan rotalarla Türk Rivierası'nın büyüsünü keşfedin.",
    "itineraries.days": "Gün",
    "itineraries.highlights": "Öne Çıkanlar",
    "itineraries.viewFull": "Tam Rotayı Gör",
    "itineraries.dayByDay": "Günlük Program",
    "itineraries.dayByDayDesc": "Yolculuğunuz özenle planlanmış duraklar ve deneyimlerle açılır.",
    "itineraries.recommendedYachts": "Önerilen Yatlar",
    "itineraries.recommendedYachtsDesc": "Bu yatlar bu rota için mükemmel şekilde uygundur.",
    "itineraries.customRoute": "Özel Rota mı Arıyorsunuz?",
    "itineraries.customRouteDesc": "Tercihlerinize göre kişiselleştirilmiş bir rota oluşturabiliriz.",
    "itineraries.requestCustom": "Özel Rota Talep Et",
    "itineraries.readyToExperience": "Bu Rotayı Deneyimlemeye Hazır mısınız?",
    "itineraries.checkAvailability": "Müsaitliği Kontrol Et",
    "itineraries.getQuote": "Teklif Al",
    "itineraries.allRoutes": "Tüm Rotalar",

    // Error Pages
    "error.pageNotFound": "Sayfa Bulunamadı",
    "error.pageNotFoundDesc": "Aradığınız sayfa denize açılmış gibi görünüyor. Belki de Türk kıyılarını keşfediyor!",
    "error.backToHome": "Ana Sayfaya Dön",
    "error.viewFleet": "Filomuzu Görün",
    "error.contactUs": "Bize Ulaşın",

    // Footer
    "footer.description": "1989'dan beri Türkiye'nin muhteşem Turkuaz Kıyıları boyunca premium gulet charterları.",
    "footer.quickLinks": "Hızlı Bağlantılar",
    "footer.contactInfo": "İletişim Bilgileri",
    "footer.followUs": "Bizi Takip Edin",
    "footer.rights": "Tüm hakları saklıdır.",
    "footer.tursab": "TÜRSAB Lisans #1739",
    "footer.workingHours": "Pzt - Cmt: 09:00 - 18:00",

    // Common
    "common.select": "Seç",
    "common.viewDetails": "Detayları Gör",
    "common.learnMore": "Daha Fazla",
    "common.callUs": "Bizi Arayın",

    // Search
    "search.placeholder": "Yat, destinasyon, güzergah ara...",
    "search.noResults": "Sonuç bulunamadı",
    "search.quickLinks": "Hızlı Bağlantılar",
    "search.hint": "Aramak için yazın",
    "search.toClose": "kapatmak için",

    // Favorites
    "favorites.title": "Favorilerim",
    "favorites.subtitle": "Kaydettiğiniz yatlar ve güzergahlar",
    "favorites.empty": "Henüz favori yok",
    "favorites.emptyDesc": "Beğendiğiniz yat ve güzergahları kalp simgesine tıklayarak kaydedin",
    "favorites.browseYachts": "Yatlara Göz At",
    "favorites.browseItineraries": "Güzergahlara Göz At",
    "favorites.yachts": "Yatlar",
    "favorites.itineraries": "Güzergahlar",
    "favorites.destinations": "Destinasyonlar",
    "favorites.clearAll": "Tümünü Temizle",
    "favorites.addedToFavorites": "Favorilere eklendi",
    "favorites.removedFromFavorites": "Favorilerden kaldırıldı",
    "common.whatsapp": "WhatsApp",
    "common.loading": "Yükleniyor...",
    "common.from": "Başlayan",
    "common.perWeek": "haftalık",
    "common.share": "Paylaş",

    // Blog
    "blog.badge": "Blogumuz",
    "blog.title": "Mavi Yolculuk Tavsiyeleri ve Seyahat İpuçları",
    "blog.subtitle": "Mükemmel yat kiralama deneyiminiz için uzman tavsiyeleri, destinasyon rehberleri ve içeriden ipuçları",
    "blog.allPosts": "Tüm Yazılar",
    "blog.destinations": "Destinasyonlar",
    "blog.tips": "İpuçları",
    "blog.guides": "Rehberler",
    "blog.news": "Haberler",
    "blog.readMore": "Devamını Oku",
    "blog.minRead": "dk okuma",
    "blog.backToBlog": "Bloga Dön",
    "blog.relatedArticles": "İlgili Makaleler",
    "blog.moreFromBlog": "Blogumuzdan Daha Fazlası",
    "blog.popularTopics": "Popüler Konular",
    "blog.readyForCruise": "Mavi Yolculuğunuza Hazır mısınız?",
    "blog.contactUsDesc": "Türk kıyıları boyunca mükemmel yat charter deneyiminizi planlamak için bizimle iletişime geçin.",
    "blog.getQuote": "Teklif Al",
    "blog.stayUpdated": "En Son Makalelerimizden Haberdar Olun",
    "blog.subscribeDesc": "Özel seyahat ipuçları, özel teklifler ve Türk kıyılarına dair rehberler için bültenimize abone olun.",
    "blog.subscribeNow": "Şimdi Abone Ol",
    "blog.shareArticle": "Bu makaleyi paylaş:",
    "blog.noPosts": "Bu kategoride yazı bulunamadı.",

    // Destinations
    "destinations.badge": "Türkiye'yi Keşfedin",
    "destinations.title": "Yelken Destinasyonları",
    "destinations.subtitle": "Türkiye'nin Turkuaz Kıyıları'nın muhteşem limanlarını ve kıyı mücevherlerini keşfedin, her biri Mavi Yolculuk maceranız için benzersiz deneyimler sunuyor",
    "destinations.turquoiseAwaits": "Turkuaz Kıyıları Sizi Bekliyor",
    "destinations.turquoiseDesc": "Türkiye'nin güneybatı kıyıları, Akdeniz'in en muhteşem yelken sularından bazılarına ev sahipliği yapıyor. Antik liman kasabalarından el değmemiş koylara kadar her destinasyon kendi karakterini ve cazibe noktalarını sunuyor.",
    "destinations.explore": "Keşfet",
    "destinations.notSure": "Nereden Başlayacağınızdan Emin Değil misiniz?",
    "destinations.notSureDesc": "Ekibimiz Türk kıyılarındaki her koyu ve limanı biliyor. Hayalinizdeki Mavi Yolculuk için mükemmel rotayı seçmenize yardımcı olalım.",
    "destinations.contactExperts": "Uzmanlarımızla İletişime Geçin",
    "destinations.about": "Hakkında",
    "destinations.whyVisit": "Neden Ziyaret Etmeli",
    "destinations.mustSee": "Görülmesi Gereken Yerler",
    "destinations.itinerariesFrom": "Rotalar -",
    "destinations.planCruise": "Planlayın",
    "destinations.planCruiseDesc": "Mükemmel Mavi Yolculuğunuzu planlamak için bizimle iletişime geçin -",
    "destinations.idealFor": "İdeal",
    "destinations.bestTime": "Ziyaret için En İyi Zaman",
    "destinations.sailInStyle": "Stil ile Yelken",
    "destinations.sailInStyleDesc": "Tamamı charter için uygun lüks gulet filomuzu keşfedin -",
    "destinations.exploreOther": "Diğer Destinasyonları Keşfedin",
    "destinations.viewAll": "Tüm Destinasyonları Gör",
    "destinations.allDestinations": "Tüm Destinasyonlar",
    "destinations.turkey": "Türkiye",

    // Newsletter
    "newsletter.title": "Bültenimize Abone Olun",
    "newsletter.subtitle": "Özel seyahat ipuçları, fırsatlar ve Türk kıyılarına dair rehberler doğrudan e-postanıza gelsin.",
    "newsletter.placeholder": "E-posta adresinizi girin",
    "newsletter.subscribe": "Şimdi Abone Ol",
    "newsletter.subscribing": "Abone olunuyor...",
    "newsletter.success": "Abone olduğunuz için teşekkürler! Onay e-postası için gelen kutunuzu kontrol edin.",
    "newsletter.error": "Bir şeyler yanlış gitti. Lütfen daha sonra tekrar deneyin.",
    "newsletter.invalidEmail": "Lütfen geçerli bir e-posta adresi girin",
    "newsletter.required": "Lütfen e-posta adresinizi girin",
    "newsletter.privacy": "Spam yok, istediğiniz zaman abonelikten çıkın. Gizliliğinize saygı duyuyoruz.",
    "newsletter.compact.title": "Bülten",
    "newsletter.compact.subtitle": "Seyahat ipuçları ve özel fırsatlar alın",
    "newsletter.compact.subscribed": "Abone oldunuz!",
  },
  de: {
    // Navigation
    "nav.home": "Startseite",
    "nav.yachts": "Unsere Yachten",
    "nav.itineraries": "Routen",
    "nav.destinations": "Reiseziele",
    "nav.about": "Über Uns",
    "nav.blog": "Blog",
    "nav.contact": "Kontakt",
    "nav.booking": "Jetzt Buchen",

    // Home Hero
    "home.hero.badge": "Luxus Blaue Reise Seit 1989",
    "home.hero.title": "Entdecken Sie die Türkische Türkisküste in Ultimativem Luxus",
    "home.hero.subtitle": "Erleben Sie eine unvergessliche Blaue Reise an Bord unserer handgefertigten Gulets. Kristallklares Wasser, antike Ruinen und Fünf-Sterne-Service erwarten Sie.",
    "home.hero.cta.fleet": "Unsere Flotte Entdecken",
    "home.hero.cta.contact": "Angebot Anfordern",

    // Home Features
    "home.features.experience.title": "35+ Jahre Erfahrung",
    "home.features.experience.desc": "Vertrauen von Tausenden Gästen seit 1989",
    "home.features.crew.title": "Professionelle Crew",
    "home.features.crew.desc": "Erfahrener Kapitän und aufmerksames Personal",
    "home.features.cuisine.title": "Gourmet-Küche",
    "home.features.cuisine.desc": "Vollpension mit mediterranen Köstlichkeiten",
    "home.features.certified.title": "TÜRSAB Zertifiziert",
    "home.features.certified.desc": "Lizenzierte Reiseagentur #1739",

    // Home Fleet
    "home.fleet.badge": "Unsere Flotte",
    "home.fleet.title": "Handgefertigte Luxus-Gulets",
    "home.fleet.subtitle": "Wählen Sie aus unserer Sammlung sorgfältig gepflegter Gulets mit einzigartigem Charakter und erstklassiger Ausstattung.",
    "home.fleet.viewAll": "Alle Yachten Ansehen",

    // Home Itineraries
    "home.itineraries.badge": "Routen",
    "home.itineraries.title": "Entdecken Sie Unsere Routen",
    "home.itineraries.subtitle": "Entdecken Sie das Beste der türkischen Riviera mit unseren sorgfältig geplanten Segelrouten.",
    "home.itineraries.viewAll": "Alle Routen Ansehen",

    // Home About
    "home.about.title": "Ihr Tor zum Mittelmeertraum",
    "home.about.desc1": "Seit 1989 kreiert Holiday Yacht unvergessliche Blaue-Reise-Erlebnisse entlang der atemberaubenden Türkisküste der Türkei. Als Teil der Light Tours Familie verbinden wir jahrzehntelange maritime Expertise mit echter türkischer Gastfreundschaft.",
    "home.about.desc2": "Unsere Flotte handgefertigter Gulets repräsentiert das Beste des traditionellen türkischen Bootsbaus, erweitert um modernen Komfort und Annehmlichkeiten.",

    // Home Stats
    "home.stats.years": "Jahre Exzellenz",
    "home.stats.yachts": "Luxus-Gulets",
    "home.stats.guests": "Zufriedene Gäste",
    "home.stats.support": "Support",
    "home.stats.satisfaction": "Zufriedenheit",
    "home.stats.destinations": "Reiseziele",

    // Home Testimonials
    "home.testimonials.badge": "Gästebewertungen",
    "home.testimonials.title": "Was Unsere Gäste Sagen",
    "home.testimonial1": "Ein absolut magisches Erlebnis! Die Crew war außergewöhnlich, das Essen war unglaublich und die Landschaft war atemberaubend. Wir kommen definitiv wieder!",
    "home.testimonial2": "Von der Buchung bis zum Verlassen war alles perfekt. Die Yacht war wunderschön und tadellos gepflegt. Der beste Urlaub, den wir je hatten!",
    "home.testimonial3": "Die Liebe zum Detail ist bemerkenswert. Schwimmen in kristallklaren Buchten und Essen unter den Sternen - besser geht es nicht.",

    // Home CTA
    "home.cta.title": "Bereit für Ihre Traumreise?",
    "home.cta.subtitle": "Lassen Sie uns Ihnen helfen, das perfekte Blaue-Reise-Erlebnis zu planen. Kontaktieren Sie uns noch heute für ein persönliches Angebot.",
    "home.cta.button": "Planen Sie Ihre Reise",

    // Home Partners
    "home.partners.partOf": "Teil von",

    // Yachts Page
    "yachts.badge": "Premium Gulet-Kollektion",
    "yachts.title": "Unsere Flotte",
    "yachts.subtitle": "Entdecken Sie unsere handverlesene Auswahl an Luxus-Gulets, die außergewöhnlichen Komfort und authentisches türkisches Handwerk bieten.",
    "yachts.stats.gulets": "Luxus-Gulets",
    "yachts.stats.capacity": "Gästekapazität",
    "yachts.stats.length": "Längenbereich",
    "yachts.stats.builtYears": "Baujahre",
    "yachts.featured": "Vorgestellte Yacht",
    "yachts.allYachts": "Alle Yachten",
    "yachts.whyChoose": "Warum Unsere Flotte Wählen?",
    "yachts.whyChooseDesc": "Jede Yacht in unserer Flotte erfüllt die höchsten Standards für Sicherheit, Komfort und Luxus.",
    "yachts.why.quality.title": "Premium-Qualität",
    "yachts.why.quality.desc": "Jede Gulet wird von Meisterschiffbauern unter Verwendung traditioneller Techniken und feinster Materialien handgefertigt.",
    "yachts.why.crew.title": "Experten-Crew",
    "yachts.why.crew.desc": "Unsere professionellen Besatzungsmitglieder sind geschult, außergewöhnlichen Service zu bieten und Ihre Sicherheit zu gewährleisten.",
    "yachts.why.amenities.title": "Moderne Ausstattung",
    "yachts.why.amenities.desc": "Genießen Sie zeitgenössischen Komfort mit Klimaanlage, WLAN und Unterhaltungssystemen.",

    // Yacht Filters
    "yachts.filters.title": "Yachten filtern",
    "yachts.filters.guests": "Gäste",
    "yachts.filters.length": "Länge",
    "yachts.filters.weeklyPrice": "Wochenpreis",
    "yachts.filters.anyGuests": "Beliebige Kapazität",
    "yachts.filters.anyLength": "Beliebige Länge",
    "yachts.filters.anyPrice": "Beliebiger Preis",
    "yachts.filters.under15k": "Unter €15.000",
    "yachts.filters.under20k": "Unter €20.000",
    "yachts.filters.under25k": "Unter €25.000",
    "yachts.filters.clear": "Filter löschen",
    "yachts.filters.active": "Aktiv",
    "yachts.filters.noResults": "Keine Yachten entsprechen Ihren Filtern",
    "yachts.filters.noResultsDesc": "Versuchen Sie, Ihre Filterkriterien anzupassen",

    // Yacht Details
    "yacht.cabins": "Kabinen",
    "yacht.guests": "Gäste",
    "yacht.length": "Länge",
    "yacht.crew": "Besatzung",
    "yacht.priceFrom": "Ab",
    "yacht.perWeek": "/Woche",
    "yacht.bookNow": "Diese Yacht Buchen",
    "yacht.requestQuote": "Angebot Anfordern",
    "yacht.amenities": "Ausstattung",
    "yacht.specifications": "Spezifikationen",
    "yacht.gallery": "Galerie",
    "yacht.overview": "Überblick",
    "yacht.features": "Merkmale",
    "yacht.seasonPrices": "Saisonpreise",
    "yacht.lowSeason": "Nebensaison",
    "yacht.midSeason": "Zwischensaison",
    "yacht.highSeason": "Hauptsaison",

    // Booking
    "booking.title": "Charter Buchen",
    "booking.subtitle": "Prüfen Sie die Verfügbarkeit und reservieren Sie Ihre Traumyacht in wenigen Schritten.",
    "booking.selectYacht": "Wählen Sie Ihre Yacht",
    "booking.selectYachtDesc": "Wählen Sie aus unserer Luxus-Gulet-Flotte.",
    "booking.selectDates": "Wählen Sie Ihre Daten",
    "booking.minNights": "Min. 7 Nächte",
    "booking.available": "Verfügbar",
    "booking.booked": "Gebucht",
    "booking.selected": "Ausgewählt",
    "booking.checkIn": "Check-in",
    "booking.checkOut": "Check-out",
    "booking.duration": "Dauer",
    "booking.nights": "Nächte",
    "booking.guestDetails": "Gastdetails",
    "booking.firstName": "Vorname",
    "booking.lastName": "Nachname",
    "booking.email": "E-Mail-Adresse",
    "booking.phone": "Telefonnummer",
    "booking.country": "Land",
    "booking.guests": "Anzahl der Gäste",
    "booking.specialRequests": "Besondere Wünsche",
    "booking.submit": "Buchung Anfragen",
    "booking.changeYacht": "← Yacht Ändern",
    "booking.whyBookDirect": "Warum Direkt Bei Uns Buchen?",
    "booking.bestPrice": "Bestpreisgarantie",
    "booking.noHiddenFees": "Keine Versteckten Gebühren",
    "booking.flexibleCancellation": "Flexible Stornierung",
    "booking.support247": "24/7 Support",
    "booking.needHelp": "Brauchen Sie Hilfe bei Ihrer Buchung?",

    // Booking Form
    "bookingForm.confirmation": "Bestätigung",
    "bookingForm.priceSummary": "Preisübersicht",
    "bookingForm.fullBoardIncluded": "Vollpension inklusive",
    "bookingForm.total": "Gesamt",
    "bookingForm.continueToDetails": "Weiter zu den Details",
    "bookingForm.guestInfo": "Gäste-Informationen",
    "bookingForm.firstNameRequired": "Vorname ist erforderlich",
    "bookingForm.lastNameRequired": "Nachname ist erforderlich",
    "bookingForm.emailRequired": "E-Mail ist erforderlich",
    "bookingForm.emailInvalid": "Ungültige E-Mail-Adresse",
    "bookingForm.phoneRequired": "Telefon ist erforderlich",
    "bookingForm.countryRequired": "Land ist erforderlich",
    "bookingForm.guest": "Gast",
    "bookingForm.specialRequestsPlaceholder": "Diätanforderungen, besondere Anlässe oder Präferenzen...",
    "bookingForm.agreeToTerms": "Ich stimme den",
    "bookingForm.termsConditions": "AGB",
    "bookingForm.and": "und der",
    "bookingForm.privacyPolicy": "Datenschutzerklärung",
    "bookingForm.termsRequired": "Sie müssen den Bedingungen zustimmen",
    "bookingForm.back": "Zurück",
    "bookingForm.requestSubmitted": "Buchungsanfrage Gesendet!",
    "bookingForm.thankYou": "Vielen Dank für Ihr Interesse an",
    "bookingForm.willContact": "Unser Team wird Ihre Anfrage prüfen und Sie innerhalb von 24 Stunden kontaktieren, um Ihre Buchung zu bestätigen.",
    "bookingForm.bookingSummary": "Buchungsübersicht",
    "bookingForm.yacht": "Yacht",
    "bookingForm.dates": "Daten",
    "bookingForm.returnHome": "Zur Startseite",

    // Calendar
    "calendar.selectDates": "Wählen Sie Ihre Termine",
    "calendar.minNights": "Min. {min} Nächte",
    "calendar.available": "Verfügbar",
    "calendar.booked": "Gebucht",
    "calendar.selected": "Ausgewählt",
    "calendar.checkIn": "Check-in",
    "calendar.checkOut": "Check-out",
    "calendar.duration": "Dauer",
    "calendar.nights": "Nächte",
    "calendar.minNightsWarning": "Bitte wählen Sie mindestens {min} Nächte",

    // Yacht Detail Page
    "yachtDetail.backToFleet": "Zurück zur Flotte",
    "yachtDetail.about": "Über",
    "yachtDetail.photoGallery": "Fotogalerie",
    "yachtDetail.amenitiesFeatures": "Ausstattung & Merkmale",
    "yachtDetail.startingFrom": "Ab",
    "yachtDetail.perWeek": "pro Woche",
    "yachtDetail.callForQuote": "Anruf für Angebot",
    "yachtDetail.sendInquiry": "Anfrage Senden",
    "yachtDetail.charterIncludes": "Charter beinhaltet:",
    "yachtDetail.professionalCrew": "Professionelle Besatzung",
    "yachtDetail.fullBoardMeals": "Vollpension",
    "yachtDetail.fuelCruising": "Treibstoff für Fahrten",
    "yachtDetail.waterSports": "Wassersportausrüstung",
    "yachtDetail.portFees": "Hafengebühren",
    "yachtDetail.built": "Baujahr",
    "yachtDetail.renovated": "Renoviert",

    // Itinerary Detail Page
    "itineraryDetail.allItineraries": "Alle Routen",
    "itineraryDetail.days": "Tage",
    "itineraryDetail.dayByDay": "Tag für Tag Reiseplan",
    "itineraryDetail.dayByDayDesc": "Ihre Reise entfaltet sich mit sorgfältig geplanten Stopps, Aktivitäten und Erlebnissen, die das Beste der Region zeigen.",
    "itineraryDetail.recommendedYachts": "Empfohlene Yachten",
    "itineraryDetail.recommendedYachtsDesc": "Diese Yachten sind perfekt für diese Route geeignet und bieten die ideale Kombination aus Komfort und Leistung.",
    "itineraryDetail.readyToExperience": "Bereit, Diese Route zu Erleben?",
    "itineraryDetail.contactUs": "Kontaktieren Sie uns, um die Verfügbarkeit zu prüfen und ein personalisiertes Angebot für Ihr Traum-Segelabenteuer zu erhalten.",
    "itineraryDetail.getQuote": "Angebot Anfordern",

    // Contact
    "contact.title": "Kontakt",
    "contact.subtitle": "Haben Sie Fragen oder sind Sie bereit, Ihre Traumreise zu buchen?",
    "contact.phone": "Telefon",
    "contact.email": "E-Mail",
    "contact.address": "Adresse",
    "contact.workingHours": "Öffnungszeiten",
    "contact.sendMessage": "Senden Sie Uns Eine Nachricht",
    "contact.sendMessageDesc": "Füllen Sie das Formular aus und wir melden uns innerhalb von 24 Stunden.",
    "contact.yourName": "Ihr Name",
    "contact.yourEmail": "E-Mail-Adresse",
    "contact.phoneNumber": "Telefonnummer",
    "contact.subject": "Betreff",
    "contact.selectSubject": "Betreff auswählen",
    "contact.subjectBooking": "Buchungsanfrage",
    "contact.subjectQuote": "Angebot Anfordern",
    "contact.subjectInfo": "Allgemeine Informationen",
    "contact.subjectCustom": "Individuelle Route",
    "contact.subjectOther": "Sonstiges",
    "contact.interestedYacht": "Interessiert an einer Yacht?",
    "contact.selectYacht": "Yacht auswählen (optional)",
    "contact.yourMessage": "Ihre Nachricht",
    "contact.messagePlaceholder": "Erzählen Sie uns von Ihrer Traumreise...",
    "contact.send": "Nachricht Senden",
    "contact.messageSent": "Nachricht Gesendet!",
    "contact.messageSentDesc": "Vielen Dank für Ihre Kontaktaufnahme.",
    "contact.sendAnother": "Weitere Nachricht Senden",
    "contact.immediateHelp": "Brauchen Sie Sofortige Hilfe?",
    "contact.immediateHelpDesc": "Unser Team ist während der Geschäftszeiten erreichbar.",

    // About
    "about.badge": "Seit 1989",
    "about.title": "Über Holiday Yacht",
    "about.subtitle": "Seit über drei Jahrzehnten unvergessliche Blaue-Reise-Erlebnisse.",
    "about.stats.years": "Jahre Erfahrung",
    "about.stats.gulets": "Luxus-Gulets",
    "about.stats.guests": "Zufriedene Gäste",
    "about.stats.destinations": "Reiseziele",
    "about.story.badge": "Unsere Geschichte",
    "about.story.title": "Ein Vermächtnis der Exzellenz an der Türkisküste",
    "about.story.p1": "Gegründet 1989 in der charmanten Küstenstadt Fethiye, begann Holiday Yacht mit einer einfachen Vision: die atemberaubende Schönheit der türkischen Mittelmeerküste mit Reisenden aus aller Welt zu teilen.",
    "about.story.p2": "Als Teil der Light Tours Familie sind wir von einem kleinen lokalen Unternehmen zu einer der angesehensten Yacht-Charter-Firmen der Region gewachsen.",
    "about.story.p3": "Heute halten wir die Werte aufrecht, die uns seit über 35 Jahren leiten: außergewöhnlicher Service, authentische Erlebnisse und unerschütterliches Engagement für Gästezufriedenheit.",
    "about.values.badge": "Unsere Werte",
    "about.values.title": "Was Uns Auszeichnet",
    "about.values.safety": "Sicherheit Zuerst",
    "about.values.safetyDesc": "Ihre Sicherheit hat höchste Priorität.",
    "about.values.hospitality": "Echte Gastfreundschaft",
    "about.values.hospitalityDesc": "Erleben Sie authentische türkische Gastfreundschaft.",
    "about.values.excellence": "Exzellenz",
    "about.values.excellenceDesc": "Wir streben in jedem Aspekt nach Exzellenz.",
    "about.values.personal": "Persönliche Note",
    "about.values.personalDesc": "Jeder Charter wird auf Ihre Wünsche zugeschnitten.",
    "about.team.badge": "Unser Team",
    "about.team.title": "Lernen Sie die Crew Kennen",
    "about.team.subtitle": "Unsere erfahrenen Besatzungsmitglieder sind das Herz von Holiday Yacht.",
    "about.team.captain": "Kapitän",
    "about.team.captainDesc": "Experten mit jahrzehntelanger Erfahrung.",
    "about.team.chef": "Koch",
    "about.team.chefDesc": "Kulinarische Künstler mit mediterraner Küche.",
    "about.team.crew": "Besatzung",
    "about.team.crewDesc": "Aufmerksames Personal für Ihren Komfort und Ihre Sicherheit.",
    "about.cta.title": "Bereit, Ihre Reise zu Beginnen?",
    "about.cta.subtitle": "Lassen Sie uns Ihnen helfen, Erinnerungen zu schaffen, die ein Leben lang halten.",
    "about.cta.fleet": "Unsere Flotte Entdecken",
    "about.cta.contact": "Kontaktieren Sie Uns",
    "about.lightTours.title": "Teil der Light Tours Familie",
    "about.lightTours.desc": "Holiday Yacht ist stolz darauf, Teil von Light Tours zu sein, einer umfassenden Reiseagentur.",

    // Itineraries
    "itineraries.badge": "Kuratierte Routen",
    "itineraries.title": "Segelrouten",
    "itineraries.subtitle": "Entdecken Sie die Magie der türkischen Riviera mit unseren fachmännisch geplanten Routen.",
    "itineraries.days": "Tage",
    "itineraries.highlights": "Highlights",
    "itineraries.viewFull": "Vollständige Route Ansehen",
    "itineraries.dayByDay": "Tag für Tag Reiseplan",
    "itineraries.dayByDayDesc": "Ihre Reise entfaltet sich mit sorgfältig geplanten Stopps und Erlebnissen.",
    "itineraries.recommendedYachts": "Empfohlene Yachten",
    "itineraries.recommendedYachtsDesc": "Diese Yachten sind perfekt für diese Route geeignet.",
    "itineraries.customRoute": "Suchen Sie eine Individuelle Route?",
    "itineraries.customRouteDesc": "Wir können eine personalisierte Route nach Ihren Wünschen erstellen.",
    "itineraries.requestCustom": "Individuelle Route Anfragen",
    "itineraries.readyToExperience": "Bereit, Diese Route zu Erleben?",
    "itineraries.checkAvailability": "Verfügbarkeit Prüfen",
    "itineraries.getQuote": "Angebot Anfordern",
    "itineraries.allRoutes": "Alle Routen",

    // Error Pages
    "error.pageNotFound": "Seite Nicht Gefunden",
    "error.pageNotFoundDesc": "Die gesuchte Seite scheint in See gestochen zu sein. Vielleicht erkundet sie gerade die türkische Küste!",
    "error.backToHome": "Zurück zur Startseite",
    "error.viewFleet": "Unsere Flotte Ansehen",
    "error.contactUs": "Kontaktieren Sie Uns",

    // Footer
    "footer.description": "Premium Gulet-Charter entlang der atemberaubenden Türkisküste seit 1989.",
    "footer.quickLinks": "Schnelllinks",
    "footer.contactInfo": "Kontaktinfo",
    "footer.followUs": "Folgen Sie Uns",
    "footer.rights": "Alle Rechte vorbehalten.",
    "footer.tursab": "TÜRSAB Lizenz #1739",
    "footer.workingHours": "Mo - Sa: 09:00 - 18:00",

    // Common
    "common.select": "Auswählen",
    "common.viewDetails": "Details Ansehen",
    "common.learnMore": "Mehr Erfahren",
    "common.callUs": "Rufen Sie Uns An",

    // Search
    "search.placeholder": "Yachten, Destinationen, Routen suchen...",
    "search.noResults": "Keine Ergebnisse gefunden",
    "search.quickLinks": "Schnelllinks",
    "search.hint": "Tippen zum Suchen",
    "search.toClose": "zum Schließen",

    // Favorites
    "favorites.title": "Meine Favoriten",
    "favorites.subtitle": "Ihre gespeicherten Yachten und Routen",
    "favorites.empty": "Noch keine Favoriten",
    "favorites.emptyDesc": "Speichern Sie Yachten und Routen, die Ihnen gefallen, indem Sie auf das Herzsymbol klicken",
    "favorites.browseYachts": "Yachten durchsuchen",
    "favorites.browseItineraries": "Routen durchsuchen",
    "favorites.yachts": "Yachten",
    "favorites.itineraries": "Routen",
    "favorites.destinations": "Destinationen",
    "favorites.clearAll": "Alle löschen",
    "favorites.addedToFavorites": "Zu Favoriten hinzugefügt",
    "favorites.removedFromFavorites": "Von Favoriten entfernt",
    "common.whatsapp": "WhatsApp",
    "common.loading": "Laden...",
    "common.from": "Ab",
    "common.perWeek": "pro Woche",
    "common.share": "Teilen",

    // Blog
    "blog.badge": "Unser Blog",
    "blog.title": "Blaue Reise Einblicke & Reisetipps",
    "blog.subtitle": "Expertenrat, Reiseführer und Insider-Tipps für Ihr perfektes Yacht-Charter-Erlebnis",
    "blog.allPosts": "Alle Beiträge",
    "blog.destinations": "Reiseziele",
    "blog.tips": "Tipps & Ratschläge",
    "blog.guides": "Reiseführer",
    "blog.news": "Neuigkeiten",
    "blog.readMore": "Weiterlesen",
    "blog.minRead": "Min. Lesezeit",
    "blog.backToBlog": "Zurück zum Blog",
    "blog.relatedArticles": "Verwandte Artikel",
    "blog.moreFromBlog": "Mehr aus unserem Blog",
    "blog.popularTopics": "Beliebte Themen",
    "blog.readyForCruise": "Bereit für Ihre Blaue Reise?",
    "blog.contactUsDesc": "Kontaktieren Sie uns, um Ihr perfektes Yachtcharter-Erlebnis entlang der türkischen Küste zu planen.",
    "blog.getQuote": "Angebot Anfordern",
    "blog.stayUpdated": "Bleiben Sie mit unseren neuesten Artikeln auf dem Laufenden",
    "blog.subscribeDesc": "Abonnieren Sie unseren Newsletter für exklusive Reisetipps, Sonderangebote und Insider-Guides zur türkischen Küste.",
    "blog.subscribeNow": "Jetzt Abonnieren",
    "blog.shareArticle": "Diesen Artikel teilen:",
    "blog.noPosts": "Keine Beiträge in dieser Kategorie gefunden.",

    // Destinations
    "destinations.badge": "Türkei Entdecken",
    "destinations.title": "Segelziele",
    "destinations.subtitle": "Entdecken Sie die atemberaubenden Häfen und Küstenjuwelen der türkischen Türkisküste, jedes mit einzigartigen Erlebnissen für Ihr Blaue-Reise-Abenteuer",
    "destinations.turquoiseAwaits": "Die Türkisküste Erwartet Sie",
    "destinations.turquoiseDesc": "Die Südwestküste der Türkei beherbergt einige der spektakulärsten Segelgewässer des Mittelmeers. Von antiken Hafenstädten bis zu unberührten Buchten bietet jedes Ziel seinen eigenen Charakter und Attraktionen.",
    "destinations.explore": "Erkunden",
    "destinations.notSure": "Nicht sicher, wo Sie anfangen sollen?",
    "destinations.notSureDesc": "Unser Team kennt jede Bucht und jeden Hafen entlang der türkischen Küste. Lassen Sie uns Ihnen helfen, die perfekte Route für Ihre Traum-Blaue-Reise zu wählen.",
    "destinations.contactExperts": "Kontaktieren Sie Unsere Experten",
    "destinations.about": "Über",
    "destinations.whyVisit": "Warum Besuchen",
    "destinations.mustSee": "Sehenswürdigkeiten",
    "destinations.itinerariesFrom": "Routen ab",
    "destinations.planCruise": "Planen Sie Ihre",
    "destinations.planCruiseDesc": "Kontaktieren Sie uns, um Ihre perfekte Blaue Reise zu planen ab",
    "destinations.idealFor": "Ideal Für",
    "destinations.bestTime": "Beste Reisezeit",
    "destinations.sailInStyle": "Segeln",
    "destinations.sailInStyleDesc": "Entdecken Sie unsere Flotte von Luxus-Gulets, alle verfügbar für Charter ab",
    "destinations.exploreOther": "Andere Ziele Erkunden",
    "destinations.viewAll": "Alle Ziele Ansehen",
    "destinations.allDestinations": "Alle Ziele",
    "destinations.turkey": "Türkei",

    // Newsletter
    "newsletter.title": "Abonnieren Sie Unseren Newsletter",
    "newsletter.subtitle": "Erhalten Sie exklusive Reisetipps, Sonderangebote und Insider-Guides zur türkischen Küste direkt in Ihren Posteingang.",
    "newsletter.placeholder": "Ihre E-Mail-Adresse eingeben",
    "newsletter.subscribe": "Jetzt Abonnieren",
    "newsletter.subscribing": "Wird abonniert...",
    "newsletter.success": "Vielen Dank für Ihre Anmeldung! Prüfen Sie Ihren Posteingang für eine Bestätigungs-E-Mail.",
    "newsletter.error": "Etwas ist schief gelaufen. Bitte versuchen Sie es später erneut.",
    "newsletter.invalidEmail": "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    "newsletter.required": "Bitte geben Sie Ihre E-Mail-Adresse ein",
    "newsletter.privacy": "Kein Spam, jederzeit abmelden. Wir respektieren Ihre Privatsphäre.",
    "newsletter.compact.title": "Newsletter",
    "newsletter.compact.subtitle": "Reisetipps & exklusive Angebote erhalten",
    "newsletter.compact.subscribed": "Abonniert!",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language;
    if (saved && ["tr", "en", "de"].includes(saved)) {
      setLanguageState(saved);
    } else {
      const browserLang = navigator.language.split("-")[0];
      if (browserLang === "tr") setLanguageState("tr");
      else if (browserLang === "de") setLanguageState("de");
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
